"""Default role definitions seeded into each tenant schema."""

DEFAULT_ROLES = [
    {
        "role_name": "ADMIN",
        "role_description": "Full system access",
        "can_import_lc": True,
        "can_upload_pdf": True,
        "can_view_dashboard": True,
        "can_edit_lc": True,
        "can_delete_lc": True,
        "can_manage_users": True,
        "can_configure_alerts": True,
        "can_view_all_lcs": True,
        "can_export_reports": True,
        "can_reopen_lc": True,
        "can_change_lc_status": True,
    },
    {
        "role_name": "MANAGER",
        "role_description": "LC management and reports",
        "can_import_lc": True,
        "can_upload_pdf": True,
        "can_view_dashboard": True,
        "can_edit_lc": True,
        "can_delete_lc": False,
        "can_manage_users": False,
        "can_configure_alerts": True,
        "can_view_all_lcs": True,
        "can_export_reports": True,
        "can_reopen_lc": False,
        "can_change_lc_status": True,
    },
    {
        "role_name": "OPERATOR",
        "role_description": "Upload and view documents",
        "can_import_lc": True,
        "can_upload_pdf": True,
        "can_view_dashboard": True,
        "can_edit_lc": False,
        "can_delete_lc": False,
        "can_manage_users": False,
        "can_configure_alerts": False,
        "can_view_all_lcs": True,
        "can_export_reports": False,
        "can_reopen_lc": False,
        "can_change_lc_status": False,
    },
    {
        "role_name": "VIEWER",
        "role_description": "Read-only access",
        "can_import_lc": False,
        "can_upload_pdf": False,
        "can_view_dashboard": True,
        "can_edit_lc": False,
        "can_delete_lc": False,
        "can_manage_users": False,
        "can_configure_alerts": False,
        "can_view_all_lcs": True,
        "can_export_reports": False,
        "can_reopen_lc": False,
        "can_change_lc_status": False,
    },
]

DEFAULT_PLANS = [
    {
        "slug": "operations",
        "name": "Operations",
        "max_users": 5,
        "max_documents_per_month": 200,
        "price_monthly": 249,
        "price_annual": 199,
        "feature_flags": {
            "whatsapp": False,
            "vessel_tracking": False,
            "report_builder": False,
            "sro_quota": False,
            "bank_limits": False,
            "roi_finance": False,
        },
    },
    {
        "slug": "trade-desk",
        "name": "Trade Desk",
        "max_users": 25,
        "max_documents_per_month": 1000,
        "price_monthly": 749,
        "price_annual": 599,
        "feature_flags": {
            "whatsapp": True,
            "vessel_tracking": True,
            "report_builder": True,
            "sro_quota": True,
            "bank_limits": True,
            "roi_finance": False,
        },
    },
    {
        "slug": "enterprise",
        "name": "Enterprise",
        "max_users": None,
        "max_documents_per_month": None,
        "price_monthly": None,
        "price_annual": None,
        "feature_flags": {
            "whatsapp": True,
            "vessel_tracking": True,
            "report_builder": True,
            "sro_quota": True,
            "bank_limits": True,
            "roi_finance": True,
            "multi_company": True,
            "audit_export": True,
            "byok": True,
        },
    },
]
